### PR TITLE
Added copy to clipboard button to resource URL

### PR DESCRIPTION
**Pull request by snobu**
Fixes https://github.com/projectkudu/ARMExplorer/issues/41

### CODE REVIEW

**Comment by davidebbo** [comment]
Actually, looks like that broke the build:

```
D:\home\site\repository\ng\manage.ts(711,12): error TS2339: Build:Property 'copyResUrlToClipboard' does not exist on type 'ArmTreeScope'. [D:\home\site\repository\ARMExplorer.csproj]
D:\home\site\repository\ng\manage.ts(720,20): error TS2339: Build:Property 'resUrlColor' does not exist on type 'ArmTreeScope'. [D:\home\site\repository\ARMExplorer.csproj]
D:\home\site\repository\ng\manage.ts(722,24): error TS2339: Build:Property 'resUrlColor' does not exist on type 'ArmTreeScope'. [D:\home\site\repository\ARMExplorer.csproj]
```

Can you take a look?

**Comment by ahmelsayed** [comment]
fixed in a48efcd0c144955acc8c8d5daca7481d196fae14

**Comment by davidebbo** [comment]
Ok, it's in Prod!

**Comment by snobu** [comment]
Thanks @ahmelsayed! I didn't get any error/warning in Visual Studio, but I compiled and tested in Debug so maybe VS was pulling some magic..

**Pull request merged**
