### PR TITLE
Adding provider metadata and operations for Microsoft.Web/connections

### PR DESCRIPTION
**Pull request by jeffhollan**
Azure Logic Apps using the connections resource.  Modifying the provider definitions so those resources and operations show

### CODE REVIEW

**Comment by davidebbo** [comment]
@shobak101 knows more about this, but I think the concern is that this json file gets generated from the swagger file. So if we edit it manually, we may lose the changes on the next update. Hosam?

**Comment by jeffhollan** [comment]
Makes sense. Let me know. I can work to figure out how to get that swagger updated with this resource if it will accomplish same result. Let me know if you have any more details.

**Comment by davidebbo** [comment]
This is kind of a new situation because you have APIs under Microsoft.Web that are not owned by our team. The way our Microsoft.Web swagger is generated is via our build process which reflects on our classes, but those classes don't contain your API.

Maybe the best approach would be for you to give us your swagger file, from which we could generate a separate Json spec, instead of trying to make it part of the same one. Is your Swagger spec available somewhere on https://github.com/Azure/azure-rest-api-specs?

**Comment by jeffhollan** [comment]
https://github.com/Azure/azure-rest-api-specs/blob/master/arm-logic/2015-02-01-preview/swagger/logic.json though looks like we'd need to tweak this a bit. For one the connections only work with 2015-08-01-preview version, and Microsoft.Web/connections operations aren't included here.

**Comment by davidebbo** [comment]
Maybe another approach is to directly write the json spec, but in a different file. i.e. right now you made changes to `Microsoft.Web.json`. What if we instead put those things in a separate file, e.g. `Microsoft.Web.Connections.json`. Explorer would consume both and avoid any merge issue later when we update our Swagger.

@shobak101 would that work?

**Comment by shobak101** [comment]
Yes @davidebbo  it should work if the same changes were just separated in a file. But I would say the generating the correct swagger is a must, whenever there are changes to the APIs or additions we need to streamline the update process.

**Pull request closed without merging**
