### PR TITLE
updaing providers list

### PR DESCRIPTION
**Pull request by shobak101**

### CODE REVIEW

**Comment by davidebbo** [comment]
Strange, it still treats is as binary :(

**Comment by shobak101** [comment]
@davidebbo yup, I just sent you an Email about that, will have to look further.

**Comment by snobu** [comment]
PowerShell scripts default to UTF-16 when saved from ISE for some reason. There may be more to this. However GitHub (actually probably git too) treats UTF-16 as binary.

**Comment by davidebbo** [comment]
@snobu You're right! I changed the script to generate utf8 and regenerated the latest.

**Comment by shobak101** [comment]
Thanks @davidebbo

**Pull request closed without merging**
