### PR TITLE
Add support for deployment logs

### PR DESCRIPTION
**Pull request by stuartleeks**
Add Microsoft.Resources provider to show deployments and operations
Provides partial implementation for #92 
With help from @shobak101 :-)

### CODE REVIEW

**Comment by davidebbo** [comment]
I didn't quite follow the client side `getTreeBranchDataOverrides` logic, but nothing looked to scary. Let's play with it in staging!

**Comment by davidebbo** [comment]
It's live in Preview! I tried it briefly and it seems to work well :)

**Comment by shobak101** [comment]
I met Stuart today and took a look at the code, it looks good. that part is to show this rp by default without having to click show all as it technically does not have any resources under it.

Sent using CloudMagic Email<https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.0.91&pv=5.1.1&source=email_footer_2>
On Thu, Jan 28, 2016 at 5:53 PM, David Ebbo <notifications@github.com<mailto:notifications@github.com>> wrote:


It's live in Preview! I tried it briefly and it seems to work well :)

-

**Comment by davidebbo** [comment]
Ah I see. Probably could use a comment :)

**Pull request merged**
